name: EventIssue
on: [issues]
jobs:
  gather_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue metadata
        run: | 
          # echo "Issue Title: ${{ github.event.issue.title }}"
          echo "${{toJson(github.event)}}"